# =====================================================================
# DEXO Control Core - 2 Motor Configuration
# Configuration for motor_control_node_2motors and trajectory_generator
# =====================================================================

# =====================================================================
# MOTOR CONTROL CONFIGURATION
# =====================================================================

# Calibration Parameters
calibration:
  sequence: [1, 2]               # Calibration order: Right hip (1), Right knee (2)
  speed_deg: 60.0                # Calibration speed in degrees/second
  max_time: 30.0                 # Maximum calibration time in seconds
  torque_thresholds: [7.0, 1.0]  # Torque thresholds [hip, knee] in Nm

# Motor Hardware Configuration
motors:
  ids: [0x06, 0x08]              # CAN IDs: [Right hip, Right knee]
  joint_names: ['right_hip', 'right_knee']
  models: ['AK80_64', 'AK80_8']  # Motor models
  directions: [1, 1]             # Direction multipliers
  
  # Joint angle limits in degrees [min, max]
  angle_limits_deg:
    - [-50, 90]   # Right hip: -50째 to 90째
    - [-100, 10]   # Right knee: -100째 to 10째

# Control Gains per Motor
control_gains:
  right_hip:
    calibration: {kp: 0.0, kd: 5.0}
    hold:        {kp: 2.0, kd: 1.5}
    trajectory:  {kp: 15.0, kd: 0.0}
  
  right_knee:
    calibration: {kp: 0.0, kd: 5.0}
    hold:        {kp: 2.0, kd: 1.5}
    trajectory:  {kp: 15.0, kd: 0.0}

# =====================================================================
# TRAJECTORY GENERATOR CONFIGURATION
# =====================================================================

trajectory_generator:
  # Timing Configuration
  control_frequency: 100         # Hz, synchronized with motor control
  
  # Leg Kinematics (meters)
  leg_parameters:
    L1: 0.44                     # Thigh length (hip to knee)
    L2: 0.44                     # Shin length (knee to ankle)
  
  # Joint Limits (degrees) - Must match motor limits above
  joint_limits:
    hip_min_deg:  -30            # Hip minimum angle
    hip_max_deg:   90            # Hip maximum angle  
    knee_min_deg: -100           # Knee minimum angle
    knee_max_deg:   0            # Knee maximum angle
  
  # Trajectory Data Configuration
  trajectory:
    file: 'gait_data_39_1.json'
    loop: true                   # Loop trajectory continuously
    scale: 1.0                   # Scaling factor for trajectory positions
    
  # State-based Output Values
  output_values:
    ready_state:   [0.0, 0.0, 0.0, 0.0]  # [hip_pos, knee_pos, hip_vel, knee_vel]
    walking_state: "trajectory_data"       # Use actual trajectory data
    stopping_state: [1.0, -1.0, 0.0, 0.0] # Safe stopping position