# Configuration for the single motor control node

# Calibration Parameters
torque_threshold: 7.0       # Nm
calibration_speed_deg: 90.0 # degrees/s
max_calibration_time: 30.0  # seconds

# Control Gains
gains:
  calibration:
    kp: 5.0
    kd: 5.0
  trajectory:
    kp: 15.0
    kd: 1.0

# Single Motor Configuration
motor:
  id: 1
  controller_id: 0x06

  joint_name: "test_motor"
  model: "AK80-64"
  angle_limits_deg: [-45, 45]
  direction: 1
